<body bgcolor="#f0f0f8">
<table width="100%" cellspacing=0 cellpadding=2 border=0 summary="heading">
<tr bgcolor="#6622aa">
<td valign=bottom>&nbsp;<br>
<font color="#ffffff" face="helvetica, arial">&nbsp;<br><big><big><strong>AttributeError</strong></big></big></font></td
><td align=right valign=bottom
><font color="#ffffff" face="helvetica, arial">Python 3.6.6: /cygdrive/d/usr/bin/python3<br>Wed Nov 21 13:43:56 2018</font></td></tr></table>
    
<p>A problem occurred in a Python script.  Here is the sequence of
function calls leading up to the error, in the order they occurred.</p>
<table width="100%" cellspacing=0 cellpadding=0 border=0>
<tr><td bgcolor="#d8bbff"><big>&nbsp;</big><a href="file://D:/XamppVirtualHost/dev/mail-formatter/main.py">D:/XamppVirtualHost/dev/mail-formatter/main.py</a> in <strong>&lt;module&gt;</strong>()</td></tr>
<tr><td><font color="#909090"><tt>&nbsp;&nbsp;<small>&nbsp;&nbsp;&nbsp;19</small>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;exit()<br>
</tt></font></td></tr>
<tr><td><font color="#909090"><tt>&nbsp;&nbsp;<small>&nbsp;&nbsp;&nbsp;20</small>&nbsp;<br>
</tt></font></td></tr>
<tr><td><font color="#909090"><tt>&nbsp;&nbsp;<small>&nbsp;&nbsp;&nbsp;21</small>&nbsp;#&nbsp;output&nbsp;=&nbsp;re.sub('\r\n|\r|\n',&nbsp;'&lt;br&gt;',&nbsp;form['mailtext'].value);<br>
</tt></font></td></tr>
<tr><td bgcolor="#ffccee"><tt>=&gt;<small>&nbsp;&nbsp;&nbsp;22</small>&nbsp;output&nbsp;=&nbsp;form['mailtext'].value.re.split('\r\n|\r|\n')<br>
</tt></td></tr>
<tr><td><font color="#909090"><tt>&nbsp;&nbsp;<small>&nbsp;&nbsp;&nbsp;23</small>&nbsp;print('&lt;p&gt;mailtext:&lt;br&gt;',&nbsp;output)<br>
</tt></font></td></tr>
<tr><td><small><font color="#909090">output <em>undefined</em>, <strong>form</strong>&nbsp;= FieldStorage(None, None, [MiniFieldStorage('mail... &gt; 長谷川\u3000なほ \r\n&gt; &gt; &gt; ＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊\r\n')]), ].<strong>value</strong>&nbsp;= [MiniFieldStorage('mailtext', '----- Original Mes... &gt; &gt; 長谷川\u3000なほ \r\n&gt; &gt; &gt; ＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊\r\n')], ].value.re <em>undefined</em></font></small></td></tr></table><p><strong>AttributeError</strong>: 'str' object has no attribute 're'
<br><tt><small>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</small>&nbsp;</tt>args&nbsp;=
("'str' object has no attribute 're'",)
<br><tt><small>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</small>&nbsp;</tt>with_traceback&nbsp;=
&lt;built-in method with_traceback of AttributeError object&gt;


<!-- The above is a description of an error in a Python program, formatted
     for a Web browser because the 'cgitb' module was enabled.  In case you
     are not reading this in a Web browser, here is the original traceback:

Traceback (most recent call last):
  File "D:/XamppVirtualHost/dev/mail-formatter/main.py", line 22, in &lt;module&gt;
    output = form['mailtext'].value.re.split('\r\n|\r|\n')
AttributeError: 'str' object has no attribute 're'

-->
